name: ParticulateRenderer
version: 0.1.0
main: group.aelysium.particulaterenderer.ParticulateRenderer
commands:
  sc:
    description: Used for all things related to ShowControl
    usage: /sc
    permission: particulate.sc
  fx:
    description: Used for running effects
    usage: /fx
    permission: particulate.fx
depend: [ProtocolLib]