########################################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
########################################################################
#                                                                      #
#          ______          _   _            _       _                  #
#          | ___ \        | | (_)          | |     | |                 #
#          | |_/ /_ _ _ __| |_ _  ___ _   _| | __ _| |_ ___            #
#          |  __/ _` | '__| __| |/ __| | | | |/ _` | __/ _ \           #
#          | | | (_| | |  | |_| | (__| |_| | | (_| | ||  __/           #
#          \_|  \__,_|_|   \__|_|\___|\__,_|_|\__,_|\__\___|           #
#                                                                      #
########################################################################
#                                                                      #
#                 Developed by: Aelysium | Nathan M.                   #
#                                                                      #
########################################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
########################################################################

########################################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#                              Websocket                               #
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
########################################################################
#
# The port number to listen on.
# Depending on your host, you may need to specifically open ports for this.
#
port: 8080